docs: Requirements: add missing `ssh` for Arch Linux
I'm not sure why, but sometimes `ssh` is needed to install Homebrew.

The commands for other distros do install `ssh`.

Logs:
```console
$ CI=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
Warning: Running in non-interactive mode because `$CI` is set.
==> Checking for `sudo` access (which may request your password)...
==> This script will install:
/home/linuxbrew/.linuxbrew/bin/brew
/home/linuxbrew/.linuxbrew/share/doc/homebrew
/home/linuxbrew/.linuxbrew/share/man/man1/brew.1
/home/linuxbrew/.linuxbrew/share/zsh/site-functions/_brew
/home/linuxbrew/.linuxbrew/etc/bash_completion.d/brew
/home/linuxbrew/.linuxbrew/Homebrew
==> /usr/bin/sudo /bin/chown -R dracula:dracula /home/linuxbrew/.linuxbrew/Homebrew
==> Found Git: /usr/sbin/git
==> Found cURL: /usr/sbin/curl
==> Setting HOMEBREW_DEVELOPER to use Git/cURL not in /usr/bin
==> Downloading and installing Homebrew...
error: cannot run ssh: No such file or directory
fatal: unable to fork
Failed during: /usr/sbin/git fetch --force origin
```

Note: this happens in `distrobox`