Warn instead of failing when `brew cleanup` is unable to remove a keg because it's owned by root
Why?

There are some formulae (like [dnsmasq(https://github.com/Homebrew/homebrew-core/blob/282b8f3948c751a9eb61a4555b1c61e547489a6e/Formula/dnsmasq.rb#L66)) that tell `brew services` to require that they be run as root. When running them as root, `brew` chowns the keg to root:
```
Warning: Taking root:admin ownership of some dnsmasq paths:
  /opt/homebrew/Cellar/dnsmasq/2.88/sbin
  /opt/homebrew/Cellar/dnsmasq/2.88/sbin/dnsmasq
  /opt/homebrew/opt/dnsmasq
  /opt/homebrew/opt/dnsmasq/sbin
  /opt/homebrew/var/homebrew/linked/dnsmasq
This will require manual removal of these paths using `sudo rm` on
brew upgrade/reinstall/uninstall.
```
This causes `brew cleanup` to fail with the message:
```
Error: Could not cleanup old kegs! Fix your permissions on:
  /opt/homebrew/Cellar/dnsmasq/2.87
```

I'd suggest that this isn't a proper failure because the dnsmasq formula is owned by root according to Homebrew's design, and there's nothing about this scenario that is "broken".

Co-authored-by: Christian Adam <christianadam@squareup.com>